### ISSUE TITLE
variable throttle?

### ISSUE THREAD

**Issue by wenzowski** [benchristel/ji#2]
Since tests are run serially, maybe swap the 300ms throttle for a moving average of suite execution time?

**Comment by wenzowski** [comment]
I was thinking of this in terms of long running tests and I didn't try writing an async test. What would that look like in `ji`?

**Comment by benchristel** [comment]
TBH, I figured no one would try such a thing. After all, Jasmine and other frameworks exist, and I'm not trying to replace them. `ji` is meant for the cases where I just want to try something out in Javascript without the overhead of setting up a Jasmine project (or maybe I'm on a chromebook where I can't just set up an npm project).

Jasmine solves the async problem by stubbing anything that could be async (Ajax, timeouts, maybe some other things) because of the fundamental problem that if the execution flow leaves the test context, the framework can't handle exceptions anymore.

**Comment by wenzowski** [comment]
Yes, of course. This is for quick fiddling only. Hmm, maybe I'll build a promise based version of it with [babel's stage-2](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=) loaded.
